// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: sidecar.proto

package sidecarpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SidecarHealthService_Check_FullMethodName = "/agentos.sidecar.v1.SidecarHealthService/Check"
)

// SidecarHealthServiceClient is the client API for SidecarHealthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SidecarHealthServiceClient interface {
	Check(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type sidecarHealthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSidecarHealthServiceClient(cc grpc.ClientConnInterface) SidecarHealthServiceClient {
	return &sidecarHealthServiceClient{cc}
}

func (c *sidecarHealthServiceClient) Check(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, SidecarHealthService_Check_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SidecarHealthServiceServer is the server API for SidecarHealthService service.
// All implementations must embed UnimplementedSidecarHealthServiceServer
// for forward compatibility.
type SidecarHealthServiceServer interface {
	Check(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedSidecarHealthServiceServer()
}

// UnimplementedSidecarHealthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSidecarHealthServiceServer struct{}

func (UnimplementedSidecarHealthServiceServer) Check(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedSidecarHealthServiceServer) mustEmbedUnimplementedSidecarHealthServiceServer() {}
func (UnimplementedSidecarHealthServiceServer) testEmbeddedByValue()                              {}

// UnsafeSidecarHealthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SidecarHealthServiceServer will
// result in compilation errors.
type UnsafeSidecarHealthServiceServer interface {
	mustEmbedUnimplementedSidecarHealthServiceServer()
}

func RegisterSidecarHealthServiceServer(s grpc.ServiceRegistrar, srv SidecarHealthServiceServer) {
	// If the following call panics, it indicates UnimplementedSidecarHealthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SidecarHealthService_ServiceDesc, srv)
}

func _SidecarHealthService_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SidecarHealthServiceServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SidecarHealthService_Check_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SidecarHealthServiceServer).Check(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SidecarHealthService_ServiceDesc is the grpc.ServiceDesc for SidecarHealthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SidecarHealthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentos.sidecar.v1.SidecarHealthService",
	HandlerType: (*SidecarHealthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _SidecarHealthService_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sidecar.proto",
}

const (
	IdentityCoreService_VerifyEd25519Challenge_FullMethodName = "/agentos.sidecar.v1.IdentityCoreService/VerifyEd25519Challenge"
)

// IdentityCoreServiceClient is the client API for IdentityCoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IdentityCoreServiceClient interface {
	VerifyEd25519Challenge(ctx context.Context, in *VerifyEd25519ChallengeRequest, opts ...grpc.CallOption) (*VerifyEd25519ChallengeResponse, error)
}

type identityCoreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityCoreServiceClient(cc grpc.ClientConnInterface) IdentityCoreServiceClient {
	return &identityCoreServiceClient{cc}
}

func (c *identityCoreServiceClient) VerifyEd25519Challenge(ctx context.Context, in *VerifyEd25519ChallengeRequest, opts ...grpc.CallOption) (*VerifyEd25519ChallengeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyEd25519ChallengeResponse)
	err := c.cc.Invoke(ctx, IdentityCoreService_VerifyEd25519Challenge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityCoreServiceServer is the server API for IdentityCoreService service.
// All implementations must embed UnimplementedIdentityCoreServiceServer
// for forward compatibility.
type IdentityCoreServiceServer interface {
	VerifyEd25519Challenge(context.Context, *VerifyEd25519ChallengeRequest) (*VerifyEd25519ChallengeResponse, error)
	mustEmbedUnimplementedIdentityCoreServiceServer()
}

// UnimplementedIdentityCoreServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIdentityCoreServiceServer struct{}

func (UnimplementedIdentityCoreServiceServer) VerifyEd25519Challenge(context.Context, *VerifyEd25519ChallengeRequest) (*VerifyEd25519ChallengeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyEd25519Challenge not implemented")
}
func (UnimplementedIdentityCoreServiceServer) mustEmbedUnimplementedIdentityCoreServiceServer() {}
func (UnimplementedIdentityCoreServiceServer) testEmbeddedByValue()                             {}

// UnsafeIdentityCoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentityCoreServiceServer will
// result in compilation errors.
type UnsafeIdentityCoreServiceServer interface {
	mustEmbedUnimplementedIdentityCoreServiceServer()
}

func RegisterIdentityCoreServiceServer(s grpc.ServiceRegistrar, srv IdentityCoreServiceServer) {
	// If the following call panics, it indicates UnimplementedIdentityCoreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IdentityCoreService_ServiceDesc, srv)
}

func _IdentityCoreService_VerifyEd25519Challenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyEd25519ChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityCoreServiceServer).VerifyEd25519Challenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityCoreService_VerifyEd25519Challenge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityCoreServiceServer).VerifyEd25519Challenge(ctx, req.(*VerifyEd25519ChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IdentityCoreService_ServiceDesc is the grpc.ServiceDesc for IdentityCoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdentityCoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentos.sidecar.v1.IdentityCoreService",
	HandlerType: (*IdentityCoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyEd25519Challenge",
			Handler:    _IdentityCoreService_VerifyEd25519Challenge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sidecar.proto",
}
