// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: sidecar.proto

package sidecarpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_sidecar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{0}
}

type HealthCheckResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Status              string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	SdkVersion          string                 `protobuf:"bytes,2,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`
	EnabledCapabilities []string               `protobuf:"bytes,3,rep,name=enabled_capabilities,json=enabledCapabilities,proto3" json:"enabled_capabilities,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_sidecar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

func (x *HealthCheckResponse) GetEnabledCapabilities() []string {
	if x != nil {
		return x.EnabledCapabilities
	}
	return nil
}

type VerifyEd25519ChallengeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Challenge     string                 `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"`
	SignatureHex  string                 `protobuf:"bytes,2,opt,name=signature_hex,json=signatureHex,proto3" json:"signature_hex,omitempty"`
	PublicKeyHex  string                 `protobuf:"bytes,3,opt,name=public_key_hex,json=publicKeyHex,proto3" json:"public_key_hex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyEd25519ChallengeRequest) Reset() {
	*x = VerifyEd25519ChallengeRequest{}
	mi := &file_sidecar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyEd25519ChallengeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyEd25519ChallengeRequest) ProtoMessage() {}

func (x *VerifyEd25519ChallengeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyEd25519ChallengeRequest.ProtoReflect.Descriptor instead.
func (*VerifyEd25519ChallengeRequest) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyEd25519ChallengeRequest) GetChallenge() string {
	if x != nil {
		return x.Challenge
	}
	return ""
}

func (x *VerifyEd25519ChallengeRequest) GetSignatureHex() string {
	if x != nil {
		return x.SignatureHex
	}
	return ""
}

func (x *VerifyEd25519ChallengeRequest) GetPublicKeyHex() string {
	if x != nil {
		return x.PublicKeyHex
	}
	return ""
}

type VerifyEd25519ChallengeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyEd25519ChallengeResponse) Reset() {
	*x = VerifyEd25519ChallengeResponse{}
	mi := &file_sidecar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyEd25519ChallengeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyEd25519ChallengeResponse) ProtoMessage() {}

func (x *VerifyEd25519ChallengeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyEd25519ChallengeResponse.ProtoReflect.Descriptor instead.
func (*VerifyEd25519ChallengeResponse) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyEd25519ChallengeResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyEd25519ChallengeResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *VerifyEd25519ChallengeResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_sidecar_proto protoreflect.FileDescriptor

const file_sidecar_proto_rawDesc = "" +
	"\n" +
	"\rsidecar.proto\x12\x12agentos.sidecar.v1\"\x14\n" +
	"\x12HealthCheckRequest\"\x81\x01\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1f\n" +
	"\vsdk_version\x18\x02 \x01(\tR\n" +
	"sdkVersion\x121\n" +
	"\x14enabled_capabilities\x18\x03 \x03(\tR\x13enabledCapabilities\"\x88\x01\n" +
	"\x1dVerifyEd25519ChallengeRequest\x12\x1c\n" +
	"\tchallenge\x18\x01 \x01(\tR\tchallenge\x12#\n" +
	"\rsignature_hex\x18\x02 \x01(\tR\fsignatureHex\x12$\n" +
	"\x0epublic_key_hex\x18\x03 \x01(\tR\fpublicKeyHex\"z\n" +
	"\x1eVerifyEd25519ChallengeResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage2p\n" +
	"\x14SidecarHealthService\x12X\n" +
	"\x05Check\x12&.agentos.sidecar.v1.HealthCheckRequest\x1a'.agentos.sidecar.v1.HealthCheckResponse2\x96\x01\n" +
	"\x13IdentityCoreService\x12\x7f\n" +
	"\x16VerifyEd25519Challenge\x121.agentos.sidecar.v1.VerifyEd25519ChallengeRequest\x1a2.agentos.sidecar.v1.VerifyEd25519ChallengeResponseBBZ@github.com/agent-os/backend/internal/sidecar/sidecarpb;sidecarpbb\x06proto3"

var (
	file_sidecar_proto_rawDescOnce sync.Once
	file_sidecar_proto_rawDescData []byte
)

func file_sidecar_proto_rawDescGZIP() []byte {
	file_sidecar_proto_rawDescOnce.Do(func() {
		file_sidecar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sidecar_proto_rawDesc), len(file_sidecar_proto_rawDesc)))
	})
	return file_sidecar_proto_rawDescData
}

var file_sidecar_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_sidecar_proto_goTypes = []any{
	(*HealthCheckRequest)(nil),             // 0: agentos.sidecar.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),            // 1: agentos.sidecar.v1.HealthCheckResponse
	(*VerifyEd25519ChallengeRequest)(nil),  // 2: agentos.sidecar.v1.VerifyEd25519ChallengeRequest
	(*VerifyEd25519ChallengeResponse)(nil), // 3: agentos.sidecar.v1.VerifyEd25519ChallengeResponse
}
var file_sidecar_proto_depIdxs = []int32{
	0, // 0: agentos.sidecar.v1.SidecarHealthService.Check:input_type -> agentos.sidecar.v1.HealthCheckRequest
	2, // 1: agentos.sidecar.v1.IdentityCoreService.VerifyEd25519Challenge:input_type -> agentos.sidecar.v1.VerifyEd25519ChallengeRequest
	1, // 2: agentos.sidecar.v1.SidecarHealthService.Check:output_type -> agentos.sidecar.v1.HealthCheckResponse
	3, // 3: agentos.sidecar.v1.IdentityCoreService.VerifyEd25519Challenge:output_type -> agentos.sidecar.v1.VerifyEd25519ChallengeResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sidecar_proto_init() }
func file_sidecar_proto_init() {
	if File_sidecar_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sidecar_proto_rawDesc), len(file_sidecar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_sidecar_proto_goTypes,
		DependencyIndexes: file_sidecar_proto_depIdxs,
		MessageInfos:      file_sidecar_proto_msgTypes,
	}.Build()
	File_sidecar_proto = out.File
	file_sidecar_proto_goTypes = nil
	file_sidecar_proto_depIdxs = nil
}
